In [2]:
import numpy as np

In [4]:
import pandas as pd

In [6]:
# Exercise 1: Create and reshape numpy array
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr1, "\n")

Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 



In [8]:
# Exercise 2: Extract elements between the 5th and 15th index
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print("Exercise 2:\n", extracted_elements, "\n")

Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15 16] 



In [10]:
# Exercise 3: Create and modify Pandas series
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruit_series['pears'] = 4
print("Exercise 3:\n", fruit_series, "\n")

Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64 



In [12]:
# Exercise 4: Create a dataframe
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen', 'Ian', 'Jack'],
    'age': [25, 34, 28, 40, 23, 35, 29, 31, 42, 30],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("Exercise 4:\n", df, "\n")


Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   34      M
2  Charlie   28      M
3    David   40      M
4     Emma   23      F
5    Frank   35      M
6    Grace   29      F
7    Helen   31      F
8      Ian   42      M
9     Jack   30      M 



In [14]:
# Exercise 5: Add an occupation column
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("Exercise 5:\n", df, "\n")

Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   34      M     Manager
2  Charlie   28      M     Analyst
3    David   40      M  Programmer
4     Emma   23      F     Manager
5    Frank   35      M     Analyst
6    Grace   29      F  Programmer
7    Helen   31      F     Manager
8      Ian   42      M     Analyst
9     Jack   30      M  Programmer 



In [16]:
# Exercise 6: Select rows where age >= 30
filtered_df = df[df['age'] >= 30]
print("Exercise 6:\n", filtered_df, "\n")


Exercise 6:
     name  age gender  occupation
1    Bob   34      M     Manager
3  David   40      M  Programmer
5  Frank   35      M     Analyst
7  Helen   31      F     Manager
8    Ian   42      M     Analyst
9   Jack   30      M  Programmer 



In [18]:
# Exercise 7: Save to CSV and read it back
df.to_csv('data.csv', index=False)
df_read = pd.read_csv('data.csv')
print("Exercise 7:\n", df_read, "\n")

Exercise 7:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   34      M     Manager
2  Charlie   28      M     Analyst
3    David   40      M  Programmer
4     Emma   23      F     Manager
5    Frank   35      M     Analyst
6    Grace   29      F  Programmer
7    Helen   31      F     Manager
8      Ian   42      M     Analyst
9     Jack   30      M  Programmer 

